- name: Set KeyRepeat
  shell: defaults write -g InitialKeyRepeat -int 18 && defaults write -g KeyRepeat -int 1

- name: create git dir
  file:
    path: ${HOME}/git
    state: directory

- name: create git template
  file:
    path: ${HOME}/.git_template/hooks
    state: directory

- name: load git template
  shell: git config --global init.templatedir '~/.git_template'