- name: write zsh installed by brew to /etc/shells
  become: true
  shell: echo /usr/local/bin/zsh >> /etc/shells

- name: set zsh to default shell
  shell: chsh -s /usr/local/bin/zsh

- name: install prezto
  git: 
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: ${HOME}/.zprezto
    force: yes

- name: copy zpreztorc
  copy:
    src: ../files/prezto/runcoms/zpreztorc
    dest: $HOME/.zprezto/runcoms/zpreztorc
    backup: yes

- name: copy zprofile
  copy:
    src: ../files/prezto/runcoms/zprofile
    dest: $HOME/.zprezto/runcoms/zprofile
    backup: yes