homebrew_taps:
  - { name: homebrew/cask }

homebrew_packages:
  - { name: jq }
  - { name: tree }
  - { name: curl }
  - { name: nkf }
  - { name: zsh }
  - { name: tig }
  - { name: graphviz }
  - { name: direnv }
  - { name: java }
  - { name: sbt }
  - { name: dart }
  - { name: go }
  - { name: starship }
  - { name: exa }

homebrew_cask_packages:
  - { name: docker }
  - { name: jetbrains-toolbox }
  - { name: visual-studio-code }
  - { name: iterm2 }
  - { name: slack }
  - { name: google-chrome }
  - { name: intellij-idea }
  - { name: trailer }
