name: Move new issues into Triage

on:
  issues:
    types: [unassigned]

jobs:
  automate-add-project:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: test
          column: backlog
          repo-token: ${{ secrets.GHPROJECT_AUTOMATION_TOKEN }}