name: Notify Milestone
on:
  workflow_dispatch:


jobs:
  notify-milestone:
    runs-on: ubuntu-latest
    steps:
      - run: npm install node-fetch
      - uses: actions/github-script@v4
        env:
          SLACK_URL: ${{secrets.SLACK_URL}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fetch = require('node-fetch');
            const milestones = await github.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            const openMilestone = milestones.data.filter(m => m.state === "open")
            const buildMessage = (milestones) => {
              return milestones.map(m => {
                return `<${m.html_url}|${m.title}>`
              })
            }
            const milestonesMessage = buildMessage(openMilestone).join("\n")
            const slackMessage = `${context.repo.owner}/${context.repo.repo}の進行中のmilestoneを通知します。\n${milestonesMessage}`
            const slackPayload = {text: slackMessage }
            fetch(process.env.SLACK_URL, { method: "POST", body: JSON.stringify(slackPayload) }).catch(err => console.error(err));

