name: Notify Milestone
on:
  workflow_dispatch:


jobs:
  create-weekly-milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const milestones = await github.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            console.log(milestones)